version: '3.9'
name: "project-stack"

services:

  my-nodejs-app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
        - my-mongodb
    networks:
      - my-network

  my-mongodb: 
    image: mongo:latest
    ports:
      - "27011:27017"
    volumes:
      - mongodb-volume:/data/db
    networks:
      - my-network

volumes:
  mongodb-volume:
    
networks:
  my-network:
     driver: bridge 
